name: VENDOR_BOOT - TWRP 2

on:
  workflow_dispatch:

jobs:
  build:
    name: Build vendor_boot by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4
        
    - name: Prepare the environment
      run: |
        sudo apt install git wget lz4 tar openssl python3 -y
      
    - name: Set Build Date # Output will be use in Release
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Prepare magiskboot
      run: |
        wget https://github.com/TeamWin/external_magisk-prebuilt/raw/android-12.1/prebuilt/magiskboot_x86_64; ls
        mv magiskboot_x86_64 magiskboot
        chmod a+x magiskboot

    - name: Prepare workspace
      run: |
        mkdir workspace; ls
        mkdir -p workspace/stock/unpack
        mkdir -p workspace/twrp/unpack

    - name: Download a copy of vendor_boot.img (stock)
      run: |
        wget https://gitlab.com/thenoobdevs2024/android_dump_samsung_a55x/-/raw/UP1A.231005.007/vendor_boot.img
        mv vendor_boot.img workspace/stock/stock-vb.img

    - name: Download a copy of vendor_boot.img (twrp)
      run: |
        wget https://github.com/cd-Crypton/samsung_a55x_vendor_boot_builder/releases/download/9737473621/vendor_boot.img
        mv vendor_boot.img workspace/twrpk/twrp-vb.img

    - name: Unpack vendor_boot.img (stock)
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/stock/unpack
        ${GITHUB_WORKSPACE}/magiskboot unpack ../stock-vb.img
        
    - name: Unpack vendor_boot.img (twrp)
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/twrp/unpack
        ${GITHUB_WORKSPACE}/magiskboot unpack ../twrp-vb.img

    - name: Replace vendor_ramdisk_recovery.cpio (twrp > stock)
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        mv twrp/unpack/vendor_ramdisk_recovery.cpio stock/unpack
        cd ${GITHUB_WORKSPACE}/workspace/stock/unpack
        ${GITHUB_WORKSPACE}/magiskboot repack ${GITHUB_WORKSPACE}/workspace/stock/stock-vb.img new-vendor_boot.img
        mv new-vendor_boot.img ${GITHUB_WORKSPACE}/vendor_boot.img
        tar -cvf twrp-vendor_boot.tar vendor_boot.img
    
    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: twrp-vendor_boot.tar
        name: Unofficial TWRP for a55x $ // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}-patched
        body: |
          # TEST
